
before_script:
    - export PATH=$PATH:~/.local/bin

pages:
    stage: deploy
    script:
    - cd doc
    - make html
    - cp -r _build/html public
    artifacts:
        paths:
        - public
    only:
    - master
